// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalApp.Infrastructure.Database;

#nullable disable

namespace SignalApp.Infrastructure.Migrations
{
    [DbContext(typeof(SignalDbContext))]
    [Migration("20251127104410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SignalApp.Domain.Models.Signal", b =>
                {
                    b.Property<int>("SignalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amplitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Frequency")
                        .HasColumnType("REAL");

                    b.Property<int>("PointsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignalType")
                        .HasColumnType("INTEGER");

                    b.HasKey("SignalId");

                    b.ToTable("Signals", (string)null);
                });

            modelBuilder.Entity("SignalApp.Domain.Models.SignalPoint", b =>
                {
                    b.Property<int>("SignalPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignalId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Time")
                        .HasColumnType("REAL");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("SignalPointId");

                    b.HasIndex("SignalId");

                    b.ToTable("SignalPoints", (string)null);
                });

            modelBuilder.Entity("SignalApp.Domain.Models.SignalPoint", b =>
                {
                    b.HasOne("SignalApp.Domain.Models.Signal", "Signal")
                        .WithMany("Points")
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("SignalApp.Domain.Models.Signal", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
